# Generated by Django 2.0 on 2019-07-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.IntegerField(choices=[(0, '全部'), (1, '男'), (2, '女')], default=0),
        ),
    ]
