# Generated by Django 2.0 on 2019-07-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190704_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_mohth',
            new_name='birth_month',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birth_yaer',
            new_name='birth_year',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('bj', '北京'), ('sz', '深圳'), ('sh', '上海'), ('cd', '成都')], max_length=64),
        ),
    ]
